set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/spi_flash.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/spi_flash.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/pjtag.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/pjtag.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/uart_printf.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/uart_printf.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/clk_and_rst.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/clk_and_rst.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/boot_mode.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/boot_mode.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/mj/rvx_tutorial_mj2/rvx_install/mini_git/imp_class_info/genesys2/pinmap/led.xdc rfile:../../../../rvx_install/mini_git/imp_class_info/genesys2/pinmap/led.xdc id:6} [current_design]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { spi_flash_scs }]; #IO_L6P_T0_FCS_B_14 Sch=flash_qspi_cs
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P24   IOSTANDARD LVCMOS33 } [get_ports { spi_flash_sdq0 }]; #IO_L1P_T0_D00_MOSI_14 Sch=flash_qspi_dq[0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R25   IOSTANDARD LVCMOS33 } [get_ports { spi_flash_sdq1 }]; #IO_L1N_T0_D01_DIN_14 Sch=flash_qspi_dq[1]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R20   IOSTANDARD LVCMOS33 } [get_ports { spi_flash_sdq[2] }]; #IO_L2P_T0_D02_14 Sch=flash_qspi_dq[2]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R21   IOSTANDARD LVCMOS33 } [get_ports { spi_flash_sdq[3] }]; #IO_L2N_T0_D03_14 Sch=flash_qspi_dq[3]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AC26  IOSTANDARD LVCMOS33 } [get_ports { pjtag_rtdo }]; #IO_L19P_T3_13 Sch=jc[1]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AJ27  IOSTANDARD LVCMOS33 } [get_ports { pjtag_rtrstnn }]; #IO_L20P_T3_13 Sch=jc[2]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AH30  IOSTANDARD LVCMOS33 } [get_ports { pjtag_rtck }]; #IO_L18N_T2_13 Sch=jc[3]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD26  IOSTANDARD LVCMOS33 } [get_ports { pjtag_rtdi }]; #IO_L19N_T3_VREF_13 Sch=jc[7]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AG30  IOSTANDARD LVCMOS33 } [get_ports { pjtag_rtms }]; #IO_L18P_T2_13 Sch=jc[8]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y23   IOSTANDARD LVCMOS33 } [get_ports { printf_tx }]; #IO_L1P_T0_12 Sch=uart_rx_out
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y20   IOSTANDARD LVCMOS33 } [get_ports { printf_rx }]; #IO_0_12 Sch=uart_tx_in
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { external_rstnn }]; #IO_0_14 Sch=cpu_resetn
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS     } [get_ports { external_clk_0_pair }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS     } [get_ports { external_clk_0 }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports external_clk_0]] 0.100
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets i_platform/i_pll0/i_xilinx_clock_pll_0/inst/clk_in1_xilinx_clock_pll_0]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G19   IOSTANDARD LVCMOS12 } [get_ports { boot_mode[0] }]; #IO_0_17 Sch=sw[0]
set_property src_info {type:XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G25   IOSTANDARD LVCMOS12 } [get_ports { boot_mode[1] }]; #IO_25_16 Sch=sw[1]
set_property src_info {type:XDC file:6 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T28    IOSTANDARD LVCMOS33 } [get_ports { led_list[0] }]; #IO_L24N_T3_35 Sch=led[4]
